[workspace]

members = [
  "ndsz-nds",
  "ndsz-fat",
  "ndsz-narc",
  "ndsz-generic-header",
  "ndsz-mknds",
  "ndsz-unnds",
  "ndsz-unnarc",
  "ndsz-bytes",
  "ndsz-util",
]

[patch."https://github.com/Zenithsiz/zutil"]
zutil = {path = "../zutil"}
